### ISSUE TITLE
Exception when knife.rb doesn't exist - even when chef-client provisioners don't exist in Vagrantfile

### ISSUE THREAD

**Issue by sneal** [sneal/vagrant-chefconfig#1]
```
/home/vagrant/.vagrant.d/gems/gems/mixlib-config-2.1.0/lib/mixlib/config.rb:47:in `read': no implicit conversion of nil into String (TypeError)
    from /home/vagrant/.vagrant.d/gems/gems/mixlib-config-2.1.0/lib/mixlib/config.rb:47:in `from_file'
    from /home/vagrant/.vagrant.d/gems/gems/vagrant-chefconfig-0.0.2/lib/vagrant-chefconfig/chef_client_configurator.rb:63:in `load_knife_config'
    from /home/vagrant/.vagrant.d/gems/gems/vagrant-chefconfig-0.0.2/lib/vagrant-chefconfig/chef_client_configurator.rb:15:in `apply_knife_config'
    from /home/vagrant/.vagrant.d/gems/gems/vagrant-chefconfig-0.0.2/lib/vagrant-chefconfig/action/load_chef_config.rb:14:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /home/vagrant/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.7/lib/berkshelf/vagrant/action/configure_chef.rb:14:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /home/vagrant/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.7/lib/berkshelf/vagrant/action/load_shelf.rb:14:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /home/vagrant/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.7/lib/berkshelf/vagrant/action/set_ui.rb:12:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/env_set.rb:19:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:147:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
    from /home/vagrant/.vagrant.d/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
    from /home/vagrant/.vagrant.d/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by sneal** [comment]
Fixed by #4
